#! /usr/bin/env python

from glob import glob
from os import remove
from shutil import rmtree

# Make a list of what to delete
files = ('rapid.exe', ) + tuple(glob('logdict*'))
dirs  = ('build', 'dist', )

# Removes the cmake files
for f in files:
    try:
        remove(f)
    except OSError:
        pass

# Removes the directories
for d in dirs:
    try:
        rmtree(d)
    except OSError:
        pass
