"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['spectral_exchange.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
           'includes' : ['sip', 'PyQt4.Qt', 'PyQt4.QtGui', 
                         'PyQt4.QtCore', 'PyQt4.Qwt5', 'PyQt4.Qwt5._iqt']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
